# Generated by Django 4.1.1 on 2023-02-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_management", "0002_post_updated_at_alter_post_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="head_image",
            field=models.ImageField(
                blank=True, upload_to="business_management/images/%Y/%m/%d/"
            ),
        ),
    ]
