# Generated by Django 4.1.1 on 2023-02-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_management", "0003_post_head_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="file_upload",
            field=models.FileField(
                blank=True, upload_to="business_management/files/%Y/%m/%d/"
            ),
        ),
    ]
