# Generated by Django 4.1.1 on 2023-02-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_management", "0004_post_file_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hook_text",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
