# Generated by Django 4.1.1 on 2023-02-11 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business_management", "0008_category_post_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category", options={"verbose_name_plural": "Categories"},
        ),
    ]
