# Generated by Django 4.1.1 on 2023-02-12 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business_management", "0009_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category", options={"verbose_name_plural": "categories"},
        ),
    ]
